# -*- coding: utf-8 -*-
"""xory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14A0zuLr-GhkfRtU96IOeLCoBesaltgrT
"""

import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

model = Sequential()
model.add(Dense(16, input_dim=2, activation="relu"))
model.add(Dense(16, input_dim=16, activation="relu"))
model.add(Dense(16, input_dim=16, activation="relu"))
model.add(Dense(16, input_dim=16, activation="relu"))
model.add(Dense(16, input_dim=16, activation="relu"))
model.add(Dense(16, input_dim=16, activation="relu"))
model.add(Dense(16, input_dim=16, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

model.compile(loss="mean_squared_error", optimizer="adam", metrics=["binary_accuracy"])

model.fit(x, y, verbose=2, epochs=500)

model.predict(x).round()