# -*- coding: utf-8 -*-
"""simple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RssFnKsS2kP3BKKyG2FzK9xfvfofJH3o

### **Simple Neeural Network (one hidden layer)**
"""

from keras.models import Sequential
from keras.layers.core import Dense
import numpy as np

x = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
y = np.array([[0], [1], [1], [0]])

model = Sequential()
model.add(Dense(4, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['binary_accuracy'])

model.fit(x, y, epochs=1500)